sprites=$(wildcard sprites/*.aseprite)
jsons=$(addprefix ./build/, $(notdir $(sprites:.aseprite=.json)))
pngs=$(addprefix ./build/, $(notdir $(sprites:.aseprite=.png)))
aseprite=../../lib/aseprite/build/bin/aseprite

all: $(jsons)

build/%.json: sprites/%.aseprite
	@mkdir -p $(dir $@)
	@$(aseprite) -b $< --sheet $(@:.json=.png) --data $@ \
	           --list-slices --format json-array\
	           --list-tags --trim

clean:
	@rm -rf export/
	@rm -rf build/
